# Note: the backends are configured per-env in separate config files. See local-backend.yml and content-backend.yml
media_folder: assets/cms-uploads
public_folder: public/build

collections:
  - name: "page"
    label: "Page"
    files:
      - label: "Contractor List"
        name: "contractors"
        preview_path: "contractors"
        file: "app/content/contractors.json"
        fields:
          - { label: Heading, name: heading, widget: string }
