site_url: https://repower-dmv-content.fly.dev
site_id: 11d3c7b6-70ab-4cc9-adb6-ffd63655d08d

backend:
  name: github
  repo: civictechdc/repower-dmv
  branch: cms-content-updates
  site_id: 11d3c7b6-70ab-4cc9-adb6-ffd63655d08d
  site_domain: 11d3c7b6-70ab-4cc9-adb6-ffd63655d08d

media_folder: assets/cms-uploads
public_folder: public/build

collections:
  - name: "page"
    label: "Page"
    files:
      - label: "Contractor List"
        name: "contractors"
        preview_path: "contractors"
        file: "app/content/contractors.json"
        fields:
          - { label: Heading, name: heading, widget: string }
